### ISSUE TITLE
GeoSeries pandas.dataframe.shift bug

### ISSUE THREAD

**Issue by beautifulpython** [arctern-io/arctern#645]
**Describe the bug**
GeoSeries did not behave as expected when it was used as input to call pandas.DataFrame.shift.
(pandas API doc : https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shift.html)

**To Reproduce**
My test code:
```python
import pandas as pd
from arctern import GeoSeries

g_s = pd.Series(["POINT (0 1)","POINT (3 5)"])
pd_df = pd.DataFrame({'s':g_s})
pd_a = pd_df.shift(periods=1,axis=1).dropna()
pd_b = pd_df.shift(periods=1,axis=0).dropna()
#pd.testing.assert_frame_equal(pd_a,pd_b)  # expected not equal (as expected)

g_s = GeoSeries(["POINT (0 1)","POINT (3 5)"])
g_df = pd.DataFrame({'s':g_s})
g_a = g_df.shift(periods=1,axis=1).dropna()
g_b = g_df.shift(periods=1,axis=0).dropna()
pd.testing.assert_frame_equal(g_a,g_b)         # expected not equal  (not as expected)
```

**Expected behavior**
Expect the shift function to behave differently when the parameters axis are 0 and 1.

**Comment by shengjh** [comment]
I think it is a pandas bug.
I run a test like this:
```
    import pandas as pd
    g_s = pd.Series(["POINT (0 1)","POINT (3 5)"], dtype='string')
    g_df = pd.DataFrame({'s':g_s, 'q':g_s})
    g_a = g_df.shift(periods=1,axis=1)
    print(g_a)
```
Got result
```
             s            q
0         <NA>         <NA>
1  POINT (0 1)  POINT (0 1)
```

**Comment by beautifulpython** [comment]
> **Reproduce**
> I run a test like this:
> 
> ```
>     import pandas as pd
>     # g_s is a Series with pandas extension string array(EA)
>     g_s = pd.Series(["POINT (0 1)","POINT (3 5)"], dtype='string')
>     g_df = pd.DataFrame({'s':g_s, 'q':g_s})
>     g_a = g_df.shift(periods=1,axis=1)
>     print(g_a)
> ```
> 
> Got result
> 
> ```
>              s            q
> 0         <NA>         <NA>
> 1  POINT (0 1)  POINT (0 1)
> ```
> 
> **Conclusion**
> I think it is a pandas bug. When `g_s` is a Series with pandas EA, will produce wrong result.

Indeed, the Pandas interface does not always behave as expected, and I did a test similar to the code in your response.
```python
import pandas as pd
from arctern import GeoSeries

pd_s = pd.Series(["POINT (0 1)","POINT (3 5)"],dtype='string')
pd_df = pd.DataFrame({'s':pd_s})
pd_a = pd_df.shift(periods=1,axis=1).dropna()
pd_b = pd_df.shift(periods=1,axis=0).dropna()
pd.testing.assert_frame_equal(pd_a,pd_b)  # not as expected
```
This case is almost the same as mentioned in the issue. All right, I will close this issue.
