### ISSUE TITLE
pandas.DataFrame.replace bug

### ISSUE THREAD

**Issue by xiaocai2333** [arctern-io/arctern#671]
**Describe the bug**
When pandas.DataFrame include arctern geoseries, the function "pandas.DataFrame.replace" doesn't work.

**To Reproduce**
1. read data to dataframe
nyc_schema = {
    "VendorID": "string",
    "tpep_pickup_datetime": "string",
    "tpep_dropoff_datetime": "string",
    "passenger_count": "int64",
    "trip_distance": "double",
    "pickup_longitude": "double",
    "pickup_latitude": "double",
    "dropoff_longitude": "double",
    "dropoff_latitude": "double",
    "fare_amount": "double",
    "tip_amount": "double",
    "total_amount": "double",
    "buildingid_pickup": "int64",
    "buildingid_dropoff": "int64",
    "buildingtext_pickup": "string",
    "buildingtext_dropoff": "string",
}

# pylint: disable=too-many-lines,unused-variable,bare-except,broad-except,unidiomatic-typecheck
TESTDATA = StringIO("""
VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,fare_amount,tip_amount,total_amount,buildingid_pickup,buildingid_dropoff,buildingtext_pickup,buildingtext_dropoff
CMT,2009-04-12 03:16:33 +00:00,2009-04-12 03:20:32 +00:00,1,1.3999999999999999,-73.993003000000002,40.747593999999999,-73.983609000000001,40.760426000000002,5.7999999999999998,0,5.7999999999999998,0,0,,"POLYGON ((-73.9833003295812 40.7590607716671,-73.983284516568 40.7590540993346,-73.9831103296997 40.7589805990397,-73.9832739116023 40.7587564485334,-73.9832848295013 40.7587414900311,-73.983320325137 40.75875646787,-73.983664080401 40.7589015182181,-73.983623439378 40.7589572077704,-73.9835486408108 40.7590597024757,-73.9834895815413 40.7591406286961,-73.9834880812315 40.7591399954262,-73.9833003295812 40.7590607716671))"
VTS,2009-04-14 11:22:00 +00:00,2009-04-14 11:38:00 +00:00,1,2.1400000000000001,-73.959907999999999,40.776353,-73.98348,40.759042000000001,10.1,2,12.1,0,150047,,"POLYGON ((-73.9833003295812 40.7590607716671,-73.983284516568 40.7590540993346,-73.9831103296997 40.7589805990397,-73.9832739116023 40.7587564485334,-73.9832848295013 40.7587414900311,-73.983320325137 40.75875646787,-73.983664080401 40.7589015182181,-73.983623439378 40.7589572077704,-73.9835486408108 40.7590597024757,-73.9834895815413 40.7591406286961,-73.9834880812315 40.7591399954262,-73.9833003295812 40.7590607716671))"
""")

df = pd.read_csv(TESTDATA,
                 dtype=nyc_schema,
                 date_parser=pd.to_datetime,
                 parse_dates=["tpep_pickup_datetime", "tpep_dropoff_datetime"])

2.Create the dataframe included arctern geoseries and geopandas geoseries.
arctern_df = df.copy()
gpd_df = df.copy()
arctern_df['test_GeoSeries'] = arctern.GeoSeries(df['buildingtext_dropoff'])
gpd_df['test_GeoSeries'] = gpd.GeoSeries(df['buildingtext_dropoff'].apply(shapely.wkt.loads)).apply(
    lambda x: x.wkb) 

3. Test function "pandas.DataFrame.replace"
def test_replace():
    arctern_replace_df = arctern_df.replace("POLYGON ((-73.9833003295812 40.7590607716671,-73.983284516568 40.7590540993346,-73.9831103296997 40.7589805990397,-73.9832739116023 40.7587564485334,-73.9832848295013 40.7587414900311,-73.983320325137 40.75875646787,-73.983664080401 40.7589015182181,-73.983623439378 40.7589572077704,-73.9835486408108 40.7590597024757,-73.9834895815413 40.7591406286961,-73.9834880812315 40.7591399954262,-73.9833003295812 40.7590607716671))", "POLYGON((1 1, 2 2, 3 3))")
    gpd_replace_df = gpd_df.replace("POLYGON ((-73.9833003295812 40.7590607716671,-73.983284516568 40.7590540993346,-73.9831103296997 40.7589805990397,-73.9832739116023 40.7587564485334,-73.9832848295013 40.7587414900311,-73.983320325137 40.75875646787,-73.983664080401 40.7589015182181,-73.983623439378 40.7589572077704,-73.9835486408108 40.7590597024757,-73.9834895815413 40.7591406286961,-73.9834880812315 40.7591399954262,-73.9833003295812 40.7590607716671))", "POLYGON((1 1, 2 2, 3 3))")

    pd.testing.assert_frame_equal(arctern_replace_df, gpd_replace_df, check_dtype=False)

**Expected behavior**
The result should modify the column of the string. The arctern geoseries is wkb. 
It seems to want to modify the column of arctern.geoseries.

**Any logs, error output, snapshot, etc?**
TypeError: Value must be bytes value, got POLYGON((1 1, 2 2, 3 3)).

**Software versions:**
 - OS: ubuntu 18.04
 - Arctern: branch-0.2.x 
 - Complie_Date: 5.30 and 6.1. (got the same result)

**Comment by shengjh** [comment]
With pandas version 1.0.3, it will work. But will failed with version 1.0.4.
I add a check in GeoArray.__set_item__(#674), it can work normally with pandas both 1.0.3 and 1.0.4.

**Comment by xiaocai2333** [comment]
Thank you very much!
