### ISSUE TITLE
memory leak in map match

### ISSUE THREAD

**Issue by nezha2017** [arctern-io/arctern#684]
**Describe the bug**

run  `map_match_tests` with `valgrind`, it shows `map_match_tests` has memory leak. 

**To Reproduce**
```bash
valgrind ./unittest/map_match/map_match_tests

==30257== 
==30257== HEAP SUMMARY:
==30257==     in use at exit: 96,311 bytes in 304 blocks
==30257==   total heap usage: 20,538 allocs, 20,234 frees, 1,880,583 bytes allocated
==30257== 
==30257== LEAK SUMMARY:
==30257==    definitely lost: 3,008 bytes in 58 blocks
==30257==    indirectly lost: 4,800 bytes in 30 blocks
==30257==      possibly lost: 432 bytes in 1 blocks
==30257==    still reachable: 88,071 bytes in 215 blocks
==30257==         suppressed: 0 bytes in 0 blocks
==30257== Rerun with --leak-check=full to see details of leaked memory
==30257== 
==30257== For counts of detected and suppressed errors, rerun with: -v
==30257== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

```

**Expected behavior**
`definitely lost` should be `zero`. 

**Any logs, error output, snapshot, etc?**
If applicable, add more infomation to help explain your problem.

**Software versions:**
 - OS:  ubuntu 16.04
 - Arctern:
```python
>>> import arctern
>>> print(arctern.version(True))
version : 0.2.0
build type : Debug/CPU 
build time : 2020-06-03 14:14.12
commit id : 5b3d581e2e687c91ed32b489f4b2044af6651d01
```

**Comment by become-nice** [comment]
> **Describe the bug**
> 
> run `map_match_tests` with `valgrind`, it shows `map_match_tests` has memory leak.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> ```shell
> valgrind ./unittest/map_match/map_match_tests
> 
> ==30257== 
> ==30257== HEAP SUMMARY:
> ==30257==     in use at exit: 96,311 bytes in 304 blocks
> ==30257==   total heap usage: 20,538 allocs, 20,234 frees, 1,880,583 bytes allocated
> ==30257== 
> ==30257== LEAK SUMMARY:
> ==30257==    definitely lost: 3,008 bytes in 58 blocks
> ==30257==    indirectly lost: 4,800 bytes in 30 blocks
> ==30257==      possibly lost: 432 bytes in 1 blocks
> ==30257==    still reachable: 88,071 bytes in 215 blocks
> ==30257==         suppressed: 0 bytes in 0 blocks
> ==30257== Rerun with --leak-check=full to see details of leaked memory
> ==30257== 
> ==30257== For counts of detected and suppressed errors, rerun with: -v
> ==30257== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> ```
> 
> **Expected behavior**
> `definitely lost` should be `zero`.
> 
> **Any logs, error output, snapshot, etc?**
> If applicable, add more infomation to help explain your problem.
> 
> **Software versions:**
> 
> * OS:  ubuntu 16.04
> * Arctern:
> 
> ```python
> >>> import arctern
> >>> print(arctern.version(True))
> version : 0.2.0
> build type : Debug/CPU 
> build time : 2020-06-03 14:14.12
> commit id : 5b3d581e2e687c91ed32b489f4b2044af6651d01
> ```

Don't destory geometry in map_match_test.cpp, it will be fixed in next pr.

**Comment by become-nice** [comment]
Don't destory geometry in map_match_test.cpp, it will be fixed in next pr.
