### ISSUE TITLE
set_axis doesn't works on arctern.GeoSeries

### ISSUE THREAD

**Issue by nezha2017** [arctern-io/arctern#692]
**Describe the bug**
`set_axis` doesn't works on arctern.GeoSeries

**To Reproduce**
```python
import arctern
import pandas as pd

p0=pd.Series([1,2,3,4],index=['a','b','c','d'])
p1=pd.Series([1,2,3,4],index=['a','b','c','d'])
p=arctern.GeoSeries.point(p0,p1)
print(p.index)
print(p0.index)
p.set_axis(p0.index)
print(p.index)
```
output
```bash
RangeIndex(start=0, stop=4, step=1)
Index(['a', 'b', 'c', 'd'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
```

**Expected behavior**
after calls `set_axis`, `p.index` should be equal with `p0.index` 

**Software versions:**
 - OS:  ubuntu 18.04
 - Arctern:
```bash
version : 0.2.0
build type : Release/CPU 
build time : 2020-06-03 14:08.36
commit id : 349e2b65db1c76466da2c9d78f26764aad0e778f
```

**Comment by shengjh** [comment]
Only the returned series of function '`set_axis` will have new index , if you don't use "inplace set_axis".
```
p=arctern.GeoSeries.point(p0,p1)
p1 = p.set_axis([1,2])
```
Only p1's index will match [1,2].

Please see pandas doc for more info: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.set_axis.html#pandas-series-set-axis
