### ISSUE TITLE
the output of GeoSeries.to_dict and GeoSeries.to_json  is diffrent with pandas.Series.to_dict and to_json

### ISSUE THREAD

**Issue by xge-zilliz** [arctern-io/arctern#697]
**Describe the bug**
the output of function s GeoSeries.to_dict and GeoSeries.to_json  is fiffrent with functions pandas.Series.to_dict and to_json

**To Reproduce**
>>> s=pd.Series(["POINT(1 2)", "POINT(2 3)"])
>>> s.to_dict()
{0: 'POINT(1 2)', 1: 'POINT(2 3)'}
>>> s=GeoSeries(s)
>>> s.to_dict()
{0: b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@', 1: b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'}
>>> 

>>> s=pd.Series(["POINT(1 2)", "POINT(2 3)"])
>>> s.to_json()
'{"0":"POINT(1 2)","1":"POINT(2 3)"}'
>>> s=GeoSeries(s)
>>> s.to_json()
'{"0":"\\u0001\\u0001\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\ud8bc\\udc00\\u0000\\u0000\\u0000\\u0000\\u0000@","1":"\\u0001\\u0001\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000@\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\b@"}'

**Expected behavior**
The output of Arctern.GeoSeries and panda.Series's functions should be the same

**Any logs, error output, snapshot, etc?**
If applicable, add more infomation to help explain your problem.

**Software versions:**
OS: Ubuntu 18.04
Arctern: version : 0.2.0

**Comment by xiaocai2333** [comment]
Arectern GeoSeries's to_dict() returns a wkb representation. To_json() now return a GeoJSON string representation of the GeoSeries. It's consistent with geopandas.
